version: '3'
services:
    gs:
        image: gluster/gluster-centos
        privileged: true
        volumes:
        - /etc/glusterfs:/etc/glusterfs
        - /var/lib/glusterd:/var/lib/glusterd
        - /var/log/glusterfs:/var/log/glusterfs
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
