---
# tasks file for docker
- name: yum update
  yum:
    name: '*'
    state: present

- name: install required packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: set up the stable repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: install Docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Add your user to the docker group.
  command: usermod -aG docker $USER
  changed_when: True

- name: Download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  tags:
    - docker-compose

- name: Create a symbolic link
  file:
    src: /usr/local/bin/docker-compose
    dest: /home/pool80/docker-compose
    owner: pool80
    group: pool80
    state: link
  tags:
    - docker-compose
